version: '3.9'

services:
    web:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        image: rails-docker
        restart: "no"
        environment:
            - DBHOST=postgresql
            - DBUSER=postgres
            - DBPASS=password
            - ENABLE_BOOTSNAP=false
        ports:
            - 3000:3000
        depends_on:
            - postgresql
        links:
            - mailcatcher
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1025:1025"
            - "1080:1080"
    postgresql:
        image: postgres
        restart: "no"
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: chucknorris_api_development
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - postgresdb:/var/lib/postgresql/data/
volumes:
    postgresdb:
